/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 03 20:12:45 GMT 2019
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BooleanExample_ESTest extends BooleanExample_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BooleanExample booleanExample0 = new BooleanExample();
      boolean boolean0 = booleanExample0.expression(true, false, true);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      BooleanExample booleanExample0 = new BooleanExample();
      boolean boolean0 = booleanExample0.expression(true, true, true);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      BooleanExample booleanExample0 = new BooleanExample();
      boolean boolean0 = booleanExample0.expression(false, false, false);
      assertFalse(boolean0);
  }
}
