/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 03 19:14:45 GMT 2019
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RecursionExample_ESTest extends RecursionExample_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RecursionExample recursionExample0 = new RecursionExample();
      int int0 = recursionExample0.sum(0);
      assertEquals(0, int0);
      
      int int1 = recursionExample0.sum(0);
      assertEquals(0, int1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RecursionExample recursionExample0 = new RecursionExample();
      int int0 = recursionExample0.sum(1281);
      int int1 = recursionExample0.sum(int0);
      int int2 = 1;
      recursionExample0.sum(int2);
      int int3 = 0;
      recursionExample0.sum(int3);
      recursionExample0.sum(int1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RecursionExample recursionExample0 = new RecursionExample();
      int int0 = 0;
      int int1 = recursionExample0.sum(0);
      int int2 = 2073;
      int int3 = recursionExample0.sum(int2);
      int int4 = 0;
      int int5 = recursionExample0.sum(int4);
      recursionExample0.sum(int5);
      recursionExample0.sum(int1);
      recursionExample0.sum(int0);
      int int6 = 0;
      recursionExample0.sum(int6);
      int int7 = recursionExample0.sum(int3);
      recursionExample0.sum(int7);
      recursionExample0.sum(int7);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RecursionExample recursionExample0 = new RecursionExample();
      recursionExample0.sum(1);
      recursionExample0.sum(0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RecursionExample recursionExample0 = new RecursionExample();
      recursionExample0.sum(1200);
      int int0 = 999;
      recursionExample0.sum(999);
      int int1 = recursionExample0.sum(int0);
      int int2 = (-1);
      recursionExample0.sum(int2);
      int int3 = 240;
      recursionExample0.sum(int3);
      recursionExample0.sum(int1);
      int int4 = 0;
      recursionExample0.sum(int4);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      RecursionExample recursionExample0 = new RecursionExample();
      recursionExample0.sum(0);
      recursionExample0.sum((-3));
  }
}
