/*
 * This file was automatically generated by EvoSuite
 * Mon Dec 02 21:43:54 GMT 2019
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SwitchExample_ESTest extends SwitchExample_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SwitchExample switchExample0 = new SwitchExample();
      String string0 = switchExample0.mod7(5);
      assertEquals("Five", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SwitchExample switchExample0 = new SwitchExample();
      String string0 = switchExample0.mod7(4);
      assertEquals("Four", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SwitchExample switchExample0 = new SwitchExample();
      String string0 = switchExample0.mod7(3);
      assertEquals("Three", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SwitchExample switchExample0 = new SwitchExample();
      String string0 = switchExample0.mod7(2);
      assertEquals("Two", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SwitchExample switchExample0 = new SwitchExample();
      String string0 = switchExample0.mod7(1);
      assertEquals("One", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SwitchExample switchExample0 = new SwitchExample();
      String string0 = switchExample0.mod7((-189));
      assertEquals("Six", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SwitchExample switchExample0 = new SwitchExample();
      String string0 = switchExample0.mod7(0);
      assertEquals("Zero", string0);
  }
}
